name: Timer.Coffee App
description: Brew delicious coffee with Timer.Coffee
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_linkify: ^5.0.2
  intl: ^0.17.0
  url_launcher: ^6.0.12
  provider: ^6.0.5
  shared_preferences: ^2.1.0
  ionicons: ^0.2.2
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/brewing_methods.json
    - assets/data/recipes_v60.json
    - assets/data/recipes_aeropress.json
    - assets/data/recipes_chemex.json
    - assets/data/recipes_frenchpress.json
    - assets/data/recipes_clever.json
    - assets/data/recipes_kalita.json
    - assets/data/coffee_facts.json
